# Generated by Django 5.0 on 2023-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_searchphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorittVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
